### ISSUE TITLE
Running make demo in virtual environment is throwing exceptions.

### ISSUE THREAD

**Issue by Prskriti** [richtier/alexa-browser-client#26]
![Screen Shot 2019-05-08 at 6 47 56 PM](https://user-images.githubusercontent.com/26160349/57377748-d6a04d00-71c0-11e9-9449-2ad695bc3a79.png)

**Comment by RAJ53AKKI** [comment]
Sir I figured out solution of this issue.
On typing make demo it was giving error message Can not import snowboy.
For fixing that I moved all files of Python3 dir of swig folder under snowboy dir.
After doing this typing make demo in virtual environment runs successfully without throwing any import error.

**Comment by richtier** [comment]
I think you need to install stuff: `make test_requirements`

**Comment by richtier** [comment]
closing this as this problem appears solved
