### ISSUE TITLE
Getting handle_command_started() missing 1 required positional argument: 'wakeword_name' on running demo on terminal side

### ISSUE THREAD

**Issue by RAJ53AKKI** [richtier/alexa-browser-client#28]
![Screen Shot 2019-07-09 at 4 46 04 PM](https://user-images.githubusercontent.com/41626158/60883618-476af080-a268-11e9-816b-e6beea7d48da.png)
Could you please help me in resolving this issue.

**Comment by richtier** [comment]
it looks like you need to upgrade the requirements. `pip install alexa-browser-client --upgrade`

**Comment by richtier** [comment]
closing this as this problem appears solved
