### ISSUE TITLE
Not getting response from AVS

### ISSUE THREAD

**Issue by RAJ53AKKI** [richtier/alexa-browser-client#29]
This is what I am getting on server side.
![Screen Shot 2019-07-12 at 5 46 24 PM](https://user-images.githubusercontent.com/41626158/61126945-70d78680-a4cb-11e9-85e5-2842f5ad068d.png)

After running make demo command server is up and running but I am not getting any response for my request on uttering word Alexa.
![WebPage](https://user-images.githubusercontent.com/41626158/61127114-f824fa00-a4cb-11e9-978a-c5b5c6061848.png)

Could you please help me in this.

**Comment by richtier** [comment]
Chrome has changed autoplay policy. This normally prevents annoying videos playing in the background before a user has interacted with the page.

See the top JavaScript warning. I'll make a PR over the next few days

**Comment by RAJ53AKKI** [comment]
May I know how long it will take to fix this issue.

**Comment by richtier** [comment]
@RAJ53AKKI it will take less than an hour of dev effort. feel free to make the change yourself if time is of the essence. [more info](https://developers.google.com/web/updates/2017/09/autoplay-policy-changes)

**Comment by RAJ53AKKI** [comment]
ohk thanks @richtier
