### ISSUE TITLE
Can alexa browser client project can be hosted remotely

### ISSUE THREAD

**Issue by Prskriti** [richtier/alexa-browser-client#31]
I have run alexa browser client on my laptop its working fantastic.I am getting response for each and every question I ask but I want to  know that Can we host this on remote server and can get response back.Is this possible if yes please guide me.
My question is having sever and client both on single machine works very well.
Will it work if we are running server remotely?

**Comment by richtier** [comment]
it sounds like what you want is multi-tier architecture. You want the user interface to be served from a different server to the backend?

this can be done, and this project is structured to allow that. It does not assume the UI will be on the same server as the code that ta;lks to AVS.

very high level steps:

1. make a repo with code that serves the UI
2. make a repo with code that handles communicating with AVS
3. make the UI talk to the API.

Explaining low level how to do that is out of the scope of this project. Stackoverflow or ask a friend or teacher to pair on it.
