### ISSUE TITLE
On running development server getting error in synchronise_device_state and websocket connection is disconnecting

### ISSUE THREAD

**Issue by Prskriti** [richtier/alexa-browser-client#36]
![device insync error](https://user-images.githubusercontent.com/26160349/65143209-06dede80-da32-11e9-92b5-6a498feff12e.png)

**Comment by Prskriti** [comment]
Could u pls tell me meaning of the line "Watching for file changes with StatReloader " which I am getting on running development server.
![Screen Shot 2019-09-18 at 5 13 57 PM](https://user-images.githubusercontent.com/26160349/65144992-24ae4280-da36-11e9-9ccc-e6afa7f70dda.png)

**Comment by richtier** [comment]
this should be fixed now. please upgrade to `alexa-browser-client==1.4.1`
